---
blogs:
  bluezone:
    name: Blue Zone
  playground:
    name: Playground
  backpages:
    name: Backpages
image_attributions:
  - '? / The Chronicle'
  - '? / Chronicle File Photo'
  - Photo Illustration by ?
  - Chronicle Graphic by ?
